language: node_js
node_js:
    - '10'
    - '12'
    - '14'
    - '15'
install:
    - npm ci
script:
    - npm run build
    - npm run test
    - npm run test:coverage

notifications:
    email: false
