# Action that triggers Jest/Puppeteer tests

name: Jest
on: [push]
jobs:
    Run-Jest:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install Jest
              run: |
                  npm install --save-dev jest babel-jest @babel/core @babel/preset-env
                  npm install --save-dev puppeteer jest-puppeteer
            - name: Run Tests
              run: npm test
