# Uses JSDoc-action
# https://github.com/marketplace/actions/jsdoc-action

name: JSDoc

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Switch Branch
              run: git switch -c docGen

            - name: Build Docs
              uses: andstor/jsdoc-action@v1
              with:
                  source_dir: ./
                  recurse: true
                  front_page: README.md
                  output_dir: ./docs

            - name: Commit Docs
              run: |
                  git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git config --local user.name "github-actions[bot]"
                  git add *
                  git commit -m "Added Docs" -a

            - name: Push Docs
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: 'docGen'

            - name: Merge Branch
              uses: everlytic/branch-merge@1.1.0
              with:
                  github_token: ${{ github.token }}
                  source_ref: 'docGen'
                  target_branch: 'main'
                  commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'

            - name: Delete Branch
              run: git push origin --delete docGen
