# Uses JSDoc-action
# https://github.com/marketplace/actions/jsdoc-action

name: GitHub pages

on:
    push
    # branches:
    #   - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Build
              uses: andstor/jsdoc-action@v1
              with:
                  source_dir:             
                    - ./scripts
                    - ./components
                  output_dir: ./docs             
                  recurse: true                  
                  #config_file: conf.json        #The path to a JSDoc configuration file.
                  #template: minami 


